version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/1
      - STORAGE_DIR=/data/storage
      - TRANSCRIPTION_ENGINE=${TRANSCRIPTION_ENGINE:-dummy}
      - TRANSLATION_ENGINE=${TRANSLATION_ENGINE:-dummy}
      - TTS_ENGINE=${TTS_ENGINE:-dummy}
      - API_PREFIX=/api
    volumes:
      - ./storage:/data/storage
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["bash", "-lc", "celery -A app.core.celery_app.celery_app worker -l info"]
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/1
      - STORAGE_DIR=/data/storage
      - TRANSCRIPTION_ENGINE=${TRANSCRIPTION_ENGINE:-dummy}
      - TRANSLATION_ENGINE=${TRANSLATION_ENGINE:-dummy}
      - TTS_ENGINE=${TTS_ENGINE:-dummy}
    volumes:
      - ./storage:/data/storage
      - ./backend/app:/app/app
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - api

networks:
  default:
    name: open-dubber-net
